title: Эхлэл
description: A simple Jekyll website deployed on GitHub Pages
baseurl: "/myjekyll" # the subpath of your site, e.g. /blog
url: "https://pythonisaur.github.io" # your GitHub Pages URL
github_username: pythonisaur
domain: pythonisaur.github.io
logo: /assets/avator.png

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/
  - README.md
